// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: github.com/kralicky/protoconfig/server/types.proto

package server

import (
	_ "github.com/kralicky/codegen/cli"
	v1 "github.com/kralicky/protoconfig/apis/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target int32

const (
	Target_ActiveConfiguration  Target = 0
	Target_DefaultConfiguration Target = 1
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "ActiveConfiguration",
		1: "DefaultConfiguration",
	}
	Target_value = map[string]int32{
		"ActiveConfiguration":  0,
		"DefaultConfiguration": 1,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kralicky_protoconfig_server_types_proto_enumTypes[0].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_github_com_kralicky_protoconfig_server_types_proto_enumTypes[0]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_server_types_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_NoAction Action = 0
	Action_Set      Action = 1
	Action_Reset    Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "NoAction",
		1: "Set",
		2: "Reset",
	}
	Action_value = map[string]int32{
		"NoAction": 0,
		"Set":      1,
		"Reset":    2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kralicky_protoconfig_server_types_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_github_com_kralicky_protoconfig_server_types_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_server_types_proto_rawDescGZIP(), []int{1}
}

// Get request options. See also: [pkg/storage.GetOptions]
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If set, will return the config at the specified revision instead of
	// the current config.
	// This revision value can be obtained from the revision field of a
	// typed GetConfiguration/GetDefaultConfiguration response, or from one of
	// the history entries in a typed ConfigurationHistory response.
	Revision *v1.Revision `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_server_types_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetRevision() *v1.Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

// History request options. See also: [pkg/storage.HistoryOptions]
type ConfigurationHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration type to return history for.
	Target Target `protobuf:"varint,1,opt,name=target,proto3,enum=server.Target" json:"target,omitempty"`
	// The latest modification revision to include in the returned history.
	Revision *v1.Revision `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// If set, will include the values of the configuration in the response.
	// Otherwise, only the revision field of each entry will be populated.
	IncludeValues bool `protobuf:"varint,3,opt,name=includeValues,proto3" json:"includeValues,omitempty"`
}

func (x *ConfigurationHistoryRequest) Reset() {
	*x = ConfigurationHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationHistoryRequest) ProtoMessage() {}

func (x *ConfigurationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationHistoryRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_server_types_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationHistoryRequest) GetTarget() Target {
	if x != nil {
		return x.Target
	}
	return Target_ActiveConfiguration
}

func (x *ConfigurationHistoryRequest) GetRevision() *v1.Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *ConfigurationHistoryRequest) GetIncludeValues() bool {
	if x != nil {
		return x.IncludeValues
	}
	return false
}

var File_github_com_kralicky_protoconfig_server_types_proto protoreflect.FileDescriptor

var file_github_com_kralicky_protoconfig_server_types_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b,
	0x79, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6c,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x40, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32,
	0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x06, 0x92, 0xc0, 0x0c, 0x02, 0x10, 0x01, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xab, 0x01, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x92, 0xc0,
	0x0c, 0x02, 0x10, 0x01, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30,
	0x0a, 0x0d, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x42, 0x0a, 0x8a, 0xc0, 0x0c, 0x06, 0x0a, 0x04, 0x74, 0x72, 0x75,
	0x65, 0x52, 0x0d, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x2a, 0x3b, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x2a, 0x2a, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x10, 0x02, 0x42, 0x30, 0x82, 0xc0, 0x0c, 0x04, 0x08,
	0x01, 0x18, 0x01, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_protoconfig_server_types_proto_rawDescOnce sync.Once
	file_github_com_kralicky_protoconfig_server_types_proto_rawDescData = file_github_com_kralicky_protoconfig_server_types_proto_rawDesc
)

func file_github_com_kralicky_protoconfig_server_types_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_protoconfig_server_types_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_protoconfig_server_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_protoconfig_server_types_proto_rawDescData)
	})
	return file_github_com_kralicky_protoconfig_server_types_proto_rawDescData
}

var file_github_com_kralicky_protoconfig_server_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_kralicky_protoconfig_server_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_kralicky_protoconfig_server_types_proto_goTypes = []interface{}{
	(Target)(0),                         // 0: server.Target
	(Action)(0),                         // 1: server.Action
	(*GetRequest)(nil),                  // 2: server.GetRequest
	(*ConfigurationHistoryRequest)(nil), // 3: server.ConfigurationHistoryRequest
	(*v1.Revision)(nil),                 // 4: core.Revision
}
var file_github_com_kralicky_protoconfig_server_types_proto_depIdxs = []int32{
	4, // 0: server.GetRequest.revision:type_name -> core.Revision
	0, // 1: server.ConfigurationHistoryRequest.target:type_name -> server.Target
	4, // 2: server.ConfigurationHistoryRequest.revision:type_name -> core.Revision
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_protoconfig_server_types_proto_init() }
func file_github_com_kralicky_protoconfig_server_types_proto_init() {
	if File_github_com_kralicky_protoconfig_server_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_server_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_protoconfig_server_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_protoconfig_server_types_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_protoconfig_server_types_proto_depIdxs,
		EnumInfos:         file_github_com_kralicky_protoconfig_server_types_proto_enumTypes,
		MessageInfos:      file_github_com_kralicky_protoconfig_server_types_proto_msgTypes,
	}.Build()
	File_github_com_kralicky_protoconfig_server_types_proto = out.File
	file_github_com_kralicky_protoconfig_server_types_proto_rawDesc = nil
	file_github_com_kralicky_protoconfig_server_types_proto_goTypes = nil
	file_github_com_kralicky_protoconfig_server_types_proto_depIdxs = nil
}
