// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: github.com/kralicky/protoconfig/apis/core/v1/core.proto

package corev1

import (
	_ "github.com/kralicky/codegen/cli"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Revision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A numerical revision uniquely identifying a specific version of the resource.
	// Larger values are newer, but this should otherwise be treated as opaque.
	Revision *int64 `protobuf:"varint,1,opt,name=revision,proto3,oneof" json:"revision,omitempty"`
	// An optional timestamp corresponding to the time the revision was created.
	// Do not depend on this field being set; if it is, it is for informational
	// purposes only.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Revision) Reset() {
	*x = Revision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Revision) GetRevision() int64 {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return 0
}

func (x *Revision) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReactiveWatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If true, uses [reactive.Bind] to watch all paths at once.
	// If false, each path recieves updates separately.
	Bind bool `protobuf:"varint,1,opt,name=bind,proto3" json:"bind,omitempty"`
	// List of paths to watch. These must be in fieldmask format.
	// The path '.' refers to the entire object.
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *ReactiveWatchRequest) Reset() {
	*x = ReactiveWatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactiveWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactiveWatchRequest) ProtoMessage() {}

func (x *ReactiveWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactiveWatchRequest.ProtoReflect.Descriptor instead.
func (*ReactiveWatchRequest) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *ReactiveWatchRequest) GetBind() bool {
	if x != nil {
		return x.Bind
	}
	return false
}

func (x *ReactiveWatchRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type ReactiveEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// In bind mode, this will contain one item for each path in the request,
	// in order. Otherwise, this will only contain a single item.
	Items []*ReactiveEvent `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ReactiveEvents) Reset() {
	*x = ReactiveEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactiveEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactiveEvents) ProtoMessage() {}

func (x *ReactiveEvents) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactiveEvents.ProtoReflect.Descriptor instead.
func (*ReactiveEvents) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *ReactiveEvents) GetItems() []*ReactiveEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReactiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path that triggered this event, as an index into the request path list.
	Index int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReactiveEvent) Reset() {
	*x = ReactiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactiveEvent) ProtoMessage() {}

func (x *ReactiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactiveEvent.ProtoReflect.Descriptor instead.
func (*ReactiveEvent) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *ReactiveEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReactiveEvent) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_github_com_kralicky_protoconfig_apis_core_v1_core_proto protoreflect.FileDescriptor

var file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDesc = []byte{
	0x0a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c,
	0x69, 0x63, 0x6b, 0x79, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x7a, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x40, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x06,
	0x8a, 0xc0, 0x0c, 0x02, 0x28, 0x01, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x40,
	0x0a, 0x14, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73,
	0x22, 0x43, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x8a, 0xc0, 0x0c, 0x02, 0x28, 0x01, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x8a, 0xc0, 0x0c, 0x02, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x3d, 0x82, 0xc0, 0x0c, 0x04, 0x08, 0x01, 0x18,
	0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72,
	0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x6f, 0x72, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescOnce sync.Once
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescData = file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDesc
)

func file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescData)
	})
	return file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDescData
}

var file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_goTypes = []interface{}{
	(*Reference)(nil),             // 0: core.Reference
	(*Revision)(nil),              // 1: core.Revision
	(*ReactiveWatchRequest)(nil),  // 2: core.ReactiveWatchRequest
	(*ReactiveEvents)(nil),        // 3: core.ReactiveEvents
	(*ReactiveEvent)(nil),         // 4: core.ReactiveEvent
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Value)(nil),                 // 6: core.Value
}
var file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_depIdxs = []int32{
	5, // 0: core.Revision.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: core.ReactiveEvents.items:type_name -> core.ReactiveEvent
	6, // 2: core.ReactiveEvent.value:type_name -> core.Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_init() }
func file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_init() {
	if File_github_com_kralicky_protoconfig_apis_core_v1_core_proto != nil {
		return
	}
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Revision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactiveWatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactiveEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_depIdxs,
		MessageInfos:      file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_msgTypes,
	}.Build()
	File_github_com_kralicky_protoconfig_apis_core_v1_core_proto = out.File
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_rawDesc = nil
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_goTypes = nil
	file_github_com_kralicky_protoconfig_apis_core_v1_core_proto_depIdxs = nil
}
