// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: github.com/kralicky/protoconfig/apis/core/v1/value.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value represents a protoreflect.Value
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Value_BoolValue
	//	*Value_Int32Value
	//	*Value_Int64Value
	//	*Value_Uint32Value
	//	*Value_Uint64Value
	//	*Value_Float32Value
	//	*Value_Float64Value
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_Enum
	//	*Value_Message
	//	*Value_List
	//	*Value_Map
	Data isValue_Data `protobuf_oneof:"data"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetData() isValue_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x, ok := x.GetData().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Value) GetInt32Value() int32 {
	if x, ok := x.GetData().(*Value_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *Value) GetInt64Value() int64 {
	if x, ok := x.GetData().(*Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *Value) GetUint32Value() uint32 {
	if x, ok := x.GetData().(*Value_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *Value) GetUint64Value() uint64 {
	if x, ok := x.GetData().(*Value_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *Value) GetFloat32Value() float32 {
	if x, ok := x.GetData().(*Value_Float32Value); ok {
		return x.Float32Value
	}
	return 0
}

func (x *Value) GetFloat64Value() float64 {
	if x, ok := x.GetData().(*Value_Float64Value); ok {
		return x.Float64Value
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x, ok := x.GetData().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x, ok := x.GetData().(*Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *Value) GetEnum() int32 {
	if x, ok := x.GetData().(*Value_Enum); ok {
		return x.Enum
	}
	return 0
}

func (x *Value) GetMessage() *anypb.Any {
	if x, ok := x.GetData().(*Value_Message); ok {
		return x.Message
	}
	return nil
}

func (x *Value) GetList() *Value_ListValue {
	if x, ok := x.GetData().(*Value_List); ok {
		return x.List
	}
	return nil
}

func (x *Value) GetMap() *Value_MapValue {
	if x, ok := x.GetData().(*Value_Map); ok {
		return x.Map
	}
	return nil
}

type isValue_Data interface {
	isValue_Data()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,4,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_Float32Value struct {
	Float32Value float32 `protobuf:"fixed32,6,opt,name=float32_value,json=float32Value,proto3,oneof"`
}

type Value_Float64Value struct {
	Float64Value float64 `protobuf:"fixed64,7,opt,name=float64_value,json=float64Value,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_Enum struct {
	Enum int32 `protobuf:"varint,10,opt,name=enum,proto3,oneof"`
}

type Value_Message struct {
	Message *anypb.Any `protobuf:"bytes,11,opt,name=message,proto3,oneof"`
}

type Value_List struct {
	List *Value_ListValue `protobuf:"bytes,12,opt,name=list,proto3,oneof"`
}

type Value_Map struct {
	Map *Value_MapValue `protobuf:"bytes,13,opt,name=map,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Data() {}

func (*Value_Int32Value) isValue_Data() {}

func (*Value_Int64Value) isValue_Data() {}

func (*Value_Uint32Value) isValue_Data() {}

func (*Value_Uint64Value) isValue_Data() {}

func (*Value_Float32Value) isValue_Data() {}

func (*Value_Float64Value) isValue_Data() {}

func (*Value_StringValue) isValue_Data() {}

func (*Value_BytesValue) isValue_Data() {}

func (*Value_Enum) isValue_Data() {}

func (*Value_Message) isValue_Data() {}

func (*Value_List) isValue_Data() {}

func (*Value_Map) isValue_Data() {}

type Value_ListValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Value_ListValue) Reset() {
	*x = Value_ListValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_ListValue) ProtoMessage() {}

func (x *Value_ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_ListValue.ProtoReflect.Descriptor instead.
func (*Value_ListValue) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Value_ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value_MapKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Value_MapKey_BoolValue
	//	*Value_MapKey_Int32Value
	//	*Value_MapKey_Int64Value
	//	*Value_MapKey_Uint32Value
	//	*Value_MapKey_Uint64Value
	//	*Value_MapKey_StringValue
	Data isValue_MapKey_Data `protobuf_oneof:"data"`
}

func (x *Value_MapKey) Reset() {
	*x = Value_MapKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_MapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_MapKey) ProtoMessage() {}

func (x *Value_MapKey) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_MapKey.ProtoReflect.Descriptor instead.
func (*Value_MapKey) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP(), []int{0, 1}
}

func (m *Value_MapKey) GetData() isValue_MapKey_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Value_MapKey) GetBoolValue() bool {
	if x, ok := x.GetData().(*Value_MapKey_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Value_MapKey) GetInt32Value() int32 {
	if x, ok := x.GetData().(*Value_MapKey_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *Value_MapKey) GetInt64Value() int64 {
	if x, ok := x.GetData().(*Value_MapKey_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *Value_MapKey) GetUint32Value() uint32 {
	if x, ok := x.GetData().(*Value_MapKey_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *Value_MapKey) GetUint64Value() uint64 {
	if x, ok := x.GetData().(*Value_MapKey_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *Value_MapKey) GetStringValue() string {
	if x, ok := x.GetData().(*Value_MapKey_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isValue_MapKey_Data interface {
	isValue_MapKey_Data()
}

type Value_MapKey_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_MapKey_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_MapKey_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_MapKey_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,4,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Value_MapKey_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_MapKey_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Value_MapKey_BoolValue) isValue_MapKey_Data() {}

func (*Value_MapKey_Int32Value) isValue_MapKey_Data() {}

func (*Value_MapKey_Int64Value) isValue_MapKey_Data() {}

func (*Value_MapKey_Uint32Value) isValue_MapKey_Data() {}

func (*Value_MapKey_Uint64Value) isValue_MapKey_Data() {}

func (*Value_MapKey_StringValue) isValue_MapKey_Data() {}

type Value_MapEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *Value_MapKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value_MapEntry) Reset() {
	*x = Value_MapEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_MapEntry) ProtoMessage() {}

func (x *Value_MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_MapEntry.ProtoReflect.Descriptor instead.
func (*Value_MapEntry) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Value_MapEntry) GetKey() *Value_MapKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Value_MapEntry) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Value_MapValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*Value_MapEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Value_MapValue) Reset() {
	*x = Value_MapValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_MapValue) ProtoMessage() {}

func (x *Value_MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_MapValue.ProtoReflect.Descriptor instead.
func (*Value_MapValue) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Value_MapValue) GetEntries() []*Value_MapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_github_com_kralicky_protoconfig_apis_core_v1_value_proto protoreflect.FileDescriptor

var file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x07, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c,
	0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33,
	0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52,
	0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a,
	0x0d, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x04,
	0x65, 0x6e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x65, 0x6e,
	0x75, 0x6d, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x1a, 0x30, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0xe6, 0x01,
	0x0a, 0x06, 0x4d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x53, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x24, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70,
	0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x3a, 0x0a, 0x08, 0x4d,
	0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72,
	0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x6f, 0x72, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescOnce sync.Once
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescData = file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDesc
)

func file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescData)
	})
	return file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDescData
}

var file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_goTypes = []interface{}{
	(*Value)(nil),           // 0: core.Value
	(*Value_ListValue)(nil), // 1: core.Value.ListValue
	(*Value_MapKey)(nil),    // 2: core.Value.MapKey
	(*Value_MapEntry)(nil),  // 3: core.Value.MapEntry
	(*Value_MapValue)(nil),  // 4: core.Value.MapValue
	(*anypb.Any)(nil),       // 5: google.protobuf.Any
}
var file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_depIdxs = []int32{
	5, // 0: core.Value.message:type_name -> google.protobuf.Any
	1, // 1: core.Value.list:type_name -> core.Value.ListValue
	4, // 2: core.Value.map:type_name -> core.Value.MapValue
	0, // 3: core.Value.ListValue.values:type_name -> core.Value
	2, // 4: core.Value.MapEntry.key:type_name -> core.Value.MapKey
	0, // 5: core.Value.MapEntry.value:type_name -> core.Value
	3, // 6: core.Value.MapValue.entries:type_name -> core.Value.MapEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_init() }
func file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_init() {
	if File_github_com_kralicky_protoconfig_apis_core_v1_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_ListValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_MapKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_MapEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_MapValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Value_BoolValue)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Uint32Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_Float32Value)(nil),
		(*Value_Float64Value)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_Enum)(nil),
		(*Value_Message)(nil),
		(*Value_List)(nil),
		(*Value_Map)(nil),
	}
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Value_MapKey_BoolValue)(nil),
		(*Value_MapKey_Int32Value)(nil),
		(*Value_MapKey_Int64Value)(nil),
		(*Value_MapKey_Uint32Value)(nil),
		(*Value_MapKey_Uint64Value)(nil),
		(*Value_MapKey_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_depIdxs,
		MessageInfos:      file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_msgTypes,
	}.Build()
	File_github_com_kralicky_protoconfig_apis_core_v1_value_proto = out.File
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_rawDesc = nil
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_goTypes = nil
	file_github_com_kralicky_protoconfig_apis_core_v1_value_proto_depIdxs = nil
}
