// Code generated by github.com/kralicky/codegen/pathbuilder. DO NOT EDIT.
// source: github.com/kralicky/protoconfig/test/ext/ext.proto

package ext

import (
	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/kralicky/protoconfig/apis/core/v1"
	protopath "google.golang.org/protobuf/reflect/protopath"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type (
	referencePathBuilder                          protopath.Path
	setRequestPathBuilder                         protopath.Path
	exampleValuePathBuilder                       protopath.Path
	fooRequestPathBuilder                         protopath.Path
	fooResponsePathBuilder                        protopath.Path
	barRequestPathBuilder                         protopath.Path
	barResponsePathBuilder                        protopath.Path
	bazRequestPathBuilder                         protopath.Path
	durationPathBuilder                           protopath.Path
	sampleConfigurationPathBuilder                protopath.Path
	revisionPathBuilder                           protopath.Path
	timestampPathBuilder                          protopath.Path
	sampleMessagePathBuilder                      protopath.Path
	sample1FieldMsgPathBuilder                    protopath.Path
	sample2FieldMsgPathBuilder                    protopath.Path
	sample3FieldMsgPathBuilder                    protopath.Path
	sample4FieldMsgPathBuilder                    protopath.Path
	sample5FieldMsgPathBuilder                    protopath.Path
	sample6FieldMsgPathBuilder                    protopath.Path
	sampleMessage2PathBuilder                     protopath.Path
	sampleGetRequestPathBuilder                   protopath.Path
	sampleSetRequestPathBuilder                   protopath.Path
	sampleDryRunRequestPathBuilder                protopath.Path
	fieldMaskPathBuilder                          protopath.Path
	sampleDryRunResponsePathBuilder               protopath.Path
	violationsPathBuilder                         protopath.Path
	violationPathBuilder                          protopath.Path
	sampleHistoryRequestPathBuilder               protopath.Path
	sampleConfigurationHistoryResponsePathBuilder protopath.Path
	sampleResetRequestPathBuilder                 protopath.Path
)

func (*Reference) ProtoPath() referencePathBuilder {
	return referencePathBuilder{protopath.Root(((*Reference)(nil)).ProtoReflect().Descriptor())}
}
func (*SetRequest) ProtoPath() setRequestPathBuilder {
	return setRequestPathBuilder{protopath.Root(((*SetRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*ExampleValue) ProtoPath() exampleValuePathBuilder {
	return exampleValuePathBuilder{protopath.Root(((*ExampleValue)(nil)).ProtoReflect().Descriptor())}
}
func (*FooRequest) ProtoPath() fooRequestPathBuilder {
	return fooRequestPathBuilder{protopath.Root(((*FooRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*FooResponse) ProtoPath() fooResponsePathBuilder {
	return fooResponsePathBuilder{protopath.Root(((*FooResponse)(nil)).ProtoReflect().Descriptor())}
}
func (*BarRequest) ProtoPath() barRequestPathBuilder {
	return barRequestPathBuilder{protopath.Root(((*BarRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*BarResponse) ProtoPath() barResponsePathBuilder {
	return barResponsePathBuilder{protopath.Root(((*BarResponse)(nil)).ProtoReflect().Descriptor())}
}
func (*BazRequest) ProtoPath() bazRequestPathBuilder {
	return bazRequestPathBuilder{protopath.Root(((*BazRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleConfiguration) ProtoPath() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder{protopath.Root(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleGetRequest) ProtoPath() sampleGetRequestPathBuilder {
	return sampleGetRequestPathBuilder{protopath.Root(((*SampleGetRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleSetRequest) ProtoPath() sampleSetRequestPathBuilder {
	return sampleSetRequestPathBuilder{protopath.Root(((*SampleSetRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleDryRunRequest) ProtoPath() sampleDryRunRequestPathBuilder {
	return sampleDryRunRequestPathBuilder{protopath.Root(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleDryRunResponse) ProtoPath() sampleDryRunResponsePathBuilder {
	return sampleDryRunResponsePathBuilder{protopath.Root(((*SampleDryRunResponse)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleHistoryRequest) ProtoPath() sampleHistoryRequestPathBuilder {
	return sampleHistoryRequestPathBuilder{protopath.Root(((*SampleHistoryRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleConfigurationHistoryResponse) ProtoPath() sampleConfigurationHistoryResponsePathBuilder {
	return sampleConfigurationHistoryResponsePathBuilder{protopath.Root(((*SampleConfigurationHistoryResponse)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleResetRequest) ProtoPath() sampleResetRequestPathBuilder {
	return sampleResetRequestPathBuilder{protopath.Root(((*SampleResetRequest)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleMessage) ProtoPath() sampleMessagePathBuilder {
	return sampleMessagePathBuilder{protopath.Root(((*SampleMessage)(nil)).ProtoReflect().Descriptor())}
}
func (*SampleMessage2) ProtoPath() sampleMessage2PathBuilder {
	return sampleMessage2PathBuilder{protopath.Root(((*SampleMessage2)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample1FieldMsg) ProtoPath() sample1FieldMsgPathBuilder {
	return sample1FieldMsgPathBuilder{protopath.Root(((*Sample1FieldMsg)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample2FieldMsg) ProtoPath() sample2FieldMsgPathBuilder {
	return sample2FieldMsgPathBuilder{protopath.Root(((*Sample2FieldMsg)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample3FieldMsg) ProtoPath() sample3FieldMsgPathBuilder {
	return sample3FieldMsgPathBuilder{protopath.Root(((*Sample3FieldMsg)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample4FieldMsg) ProtoPath() sample4FieldMsgPathBuilder {
	return sample4FieldMsgPathBuilder{protopath.Root(((*Sample4FieldMsg)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample5FieldMsg) ProtoPath() sample5FieldMsgPathBuilder {
	return sample5FieldMsgPathBuilder{protopath.Root(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor())}
}
func (*Sample6FieldMsg) ProtoPath() sample6FieldMsgPathBuilder {
	return sample6FieldMsgPathBuilder{protopath.Root(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor())}
}

func (p setRequestPathBuilder) Node() referencePathBuilder {
	return referencePathBuilder(append(p, protopath.FieldAccess(((*SetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p setRequestPathBuilder) Example() exampleValuePathBuilder {
	return exampleValuePathBuilder(append(p, protopath.FieldAccess(((*SetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p bazRequestPathBuilder) ParamDuration() durationPathBuilder {
	return durationPathBuilder(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(12))))
}
func (p bazRequestPathBuilder) ParamMsg() bazRequestPathBuilder {
	return bazRequestPathBuilder(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(14))))
}
func (p sampleConfigurationPathBuilder) Revision() revisionPathBuilder {
	return revisionPathBuilder(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleConfigurationPathBuilder) MessageField() sampleMessagePathBuilder {
	return sampleMessagePathBuilder(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(8))))
}
func (p revisionPathBuilder) Timestamp() timestampPathBuilder {
	return timestampPathBuilder(append(p, protopath.FieldAccess(((*v1.Revision)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleMessagePathBuilder) Field1() sample1FieldMsgPathBuilder {
	return sample1FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleMessagePathBuilder) Field2() sample2FieldMsgPathBuilder {
	return sample2FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleMessagePathBuilder) Field3() sample3FieldMsgPathBuilder {
	return sample3FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sampleMessagePathBuilder) Field4() sample4FieldMsgPathBuilder {
	return sample4FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sampleMessagePathBuilder) Field5() sample5FieldMsgPathBuilder {
	return sample5FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sampleMessagePathBuilder) Field6() sample6FieldMsgPathBuilder {
	return sample6FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(6))))
}
func (p sampleMessagePathBuilder) Msg() sampleMessage2PathBuilder {
	return sampleMessage2PathBuilder(append(p, protopath.FieldAccess(((*SampleMessage)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(7))))
}
func (p sampleMessage2PathBuilder) Field1() sample1FieldMsgPathBuilder {
	return sample1FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleMessage2PathBuilder) Field2() sample2FieldMsgPathBuilder {
	return sample2FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleMessage2PathBuilder) Field3() sample3FieldMsgPathBuilder {
	return sample3FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sampleMessage2PathBuilder) Field4() sample4FieldMsgPathBuilder {
	return sample4FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sampleMessage2PathBuilder) Field5() sample5FieldMsgPathBuilder {
	return sample5FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sampleMessage2PathBuilder) Field6() sample6FieldMsgPathBuilder {
	return sample6FieldMsgPathBuilder(append(p, protopath.FieldAccess(((*SampleMessage2)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(6))))
}
func (p sampleGetRequestPathBuilder) Revision() revisionPathBuilder {
	return revisionPathBuilder(append(p, protopath.FieldAccess(((*SampleGetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleSetRequestPathBuilder) Spec() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleSetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleDryRunRequestPathBuilder) Spec() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sampleDryRunRequestPathBuilder) Revision() revisionPathBuilder {
	return revisionPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sampleDryRunRequestPathBuilder) Mask() fieldMaskPathBuilder {
	return fieldMaskPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sampleDryRunRequestPathBuilder) Patch() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(6))))
}
func (p sampleDryRunResponsePathBuilder) Current() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleDryRunResponsePathBuilder) Modified() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleDryRunResponsePathBuilder) ValidationErrors() violationsPathBuilder {
	return violationsPathBuilder(append(p, protopath.FieldAccess(((*SampleDryRunResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p violationsPathBuilder) Violations(idx int) violationPathBuilder {
	return violationPathBuilder(append(p, protopath.FieldAccess(((*validate.Violations)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1)), protopath.ListIndex(idx)))
}
func (p sampleHistoryRequestPathBuilder) Revision() revisionPathBuilder {
	return revisionPathBuilder(append(p, protopath.FieldAccess(((*SampleHistoryRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleConfigurationHistoryResponsePathBuilder) Entries(idx int) sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleConfigurationHistoryResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1)), protopath.ListIndex(idx)))
}
func (p sampleResetRequestPathBuilder) Revision() revisionPathBuilder {
	return revisionPathBuilder(append(p, protopath.FieldAccess(((*SampleResetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleResetRequestPathBuilder) Mask() fieldMaskPathBuilder {
	return fieldMaskPathBuilder(append(p, protopath.FieldAccess(((*SampleResetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleResetRequestPathBuilder) Patch() sampleConfigurationPathBuilder {
	return sampleConfigurationPathBuilder(append(p, protopath.FieldAccess(((*SampleResetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}

func (p referencePathBuilder) Id() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Reference)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p setRequestPathBuilder) Value() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p exampleValuePathBuilder) Value() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*ExampleValue)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p fooRequestPathBuilder) Request() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FooRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p fooResponsePathBuilder) Response() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FooResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p barRequestPathBuilder) Param1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p barRequestPathBuilder) Param2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p barRequestPathBuilder) Param3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p barResponsePathBuilder) Param1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p barResponsePathBuilder) Param2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p barResponsePathBuilder) Param3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BarResponse)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p bazRequestPathBuilder) ParamFloat64() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p bazRequestPathBuilder) ParamInt64() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p bazRequestPathBuilder) ParamBool() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(8))))
}
func (p bazRequestPathBuilder) ParamString() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(9))))
}
func (p bazRequestPathBuilder) ParamBytes() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
func (p bazRequestPathBuilder) ParamEnum() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(11))))
}
func (p bazRequestPathBuilder) ParamRepeatedString(idx int) protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*BazRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(13)), protopath.ListIndex(idx)))
}
func (p durationPathBuilder) Seconds() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*durationpb.Duration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p durationPathBuilder) Nanos() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*durationpb.Duration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sampleConfigurationPathBuilder) Enabled() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleConfigurationPathBuilder) StringField() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sampleConfigurationPathBuilder) SecretField() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sampleConfigurationPathBuilder) MapField() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sampleConfigurationPathBuilder) RepeatedField(idx int) protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(6)), protopath.ListIndex(idx)))
}
func (p sampleConfigurationPathBuilder) EnumField() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleConfiguration)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(7))))
}
func (p revisionPathBuilder) Revision() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*v1.Revision)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p timestampPathBuilder) Seconds() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*timestamppb.Timestamp)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p timestampPathBuilder) Nanos() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*timestamppb.Timestamp)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample1FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample1FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample2FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample2FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample2FieldMsgPathBuilder) Field2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample2FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample3FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample3FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample3FieldMsgPathBuilder) Field2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample3FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample3FieldMsgPathBuilder) Field3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample3FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sample4FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample4FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample4FieldMsgPathBuilder) Field2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample4FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample4FieldMsgPathBuilder) Field3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample4FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sample4FieldMsgPathBuilder) Field4() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample4FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sample5FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample5FieldMsgPathBuilder) Field2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample5FieldMsgPathBuilder) Field3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sample5FieldMsgPathBuilder) Field4() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sample5FieldMsgPathBuilder) Field5() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample5FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sample6FieldMsgPathBuilder) Field1() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sample6FieldMsgPathBuilder) Field2() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p sample6FieldMsgPathBuilder) Field3() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sample6FieldMsgPathBuilder) Field4() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sample6FieldMsgPathBuilder) Field5() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p sample6FieldMsgPathBuilder) Field6() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*Sample6FieldMsg)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(6))))
}
func (p sampleGetRequestPathBuilder) Key() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleGetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
func (p sampleSetRequestPathBuilder) Key() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleSetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
func (p sampleDryRunRequestPathBuilder) Key() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
func (p sampleDryRunRequestPathBuilder) Target() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleDryRunRequestPathBuilder) Action() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleDryRunRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p fieldMaskPathBuilder) Paths(idx int) protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*fieldmaskpb.FieldMask)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1)), protopath.ListIndex(idx)))
}
func (p violationPathBuilder) FieldPath() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*validate.Violation)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p violationPathBuilder) ConstraintId() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*validate.Violation)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p violationPathBuilder) Message() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*validate.Violation)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p violationPathBuilder) ForKey() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*validate.Violation)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p sampleHistoryRequestPathBuilder) Key() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleHistoryRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
func (p sampleHistoryRequestPathBuilder) Target() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleHistoryRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p sampleHistoryRequestPathBuilder) IncludeValues() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleHistoryRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p sampleResetRequestPathBuilder) Key() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*SampleResetRequest)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(10))))
}
